### ISSUE TITLE
build module fail in nginx1.8

### ISSUE THREAD

**Issue by helinb** [slact/nginx_http_push_module#101]
../nginx_http_push_module-0.73/src/ngx_http_push_module.c: 在函数‘ngx_http_push_respond_to_subscribers’中:
../nginx_http_push_module-0.73/src/ngx_http_push_module.c:711:30: 错误：此函数中的‘buf_use_count’在使用前可能未初始化 [-Werror=maybe-uninitialized]
       clndata->buf_use_count = buf_use_count;
                              ^
../nginx_http_push_module-0.73/src/ngx_http_push_module.c:673:14: 附注：‘buf_use_count’在此声明
   ngx_int_t                  *buf_use_count;
              ^
cc1: all warnings being treated as errors
objs/Makefile:2029: recipe for target 'objs/addon/src/ngx_http_push_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_push_module.o] Error 1
make[1]: Leaving directory '/tmp/makepkg/nginx/src/nginx-1.8.0'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by slact** [comment]
fixed in v0.731 . I've actually had this fixed in master for over a year, I just never tagged it as most people have no problem with it.
